version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  deploy-s3:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - .
      - aws-s3/sync:
          arguments: --acl public-read
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: .
          to: "s3://nugaspam.com"
      - aws-s3/copy:
          arguments: "--dryrun"
          from: .
          to: "s3://nugaspam.com"

workflows:
  deploy-frontend:
    jobs:
      - deploy-s3:
        filters:
          branches:
            only: main
